export const designTokensCSS = `:root{--apple-card-radius:22px;--apple-modal-radius:22px;--apple-chip-radius:50px;--apple-input-radius:10px;--apple-toggle-radius:11px;--apple-button-radius:50%;--apple-action-btn-size:40px;--apple-action-icon-size:22px;--apple-card-height:70px;--apple-card-icon-size:40px;--apple-card-icon-font-size:24px;--apple-camera-height:220px;--apple-title-size:28px;--apple-section-title-size:17px;--apple-card-name-size:15px;--apple-card-state-size:13px;--apple-temp-font-size-regular:16px;--apple-temp-font-size-tall:40px;--apple-chip-height:32px;--apple-chip-padding:3px 16px 3px 8px;--apple-chip-gap:6px;--apple-chip-icon-size:24px;--apple-chip-name-size:13px;--apple-chip-status-size:11px;--apple-section-gap:20px;--apple-card-gap:10px;--apple-card-padding:10px;--apple-page-padding:22px;--apple-page-padding-bottom:22px;--apple-card-bg-inactive:rgba(0,0,0,.25);--apple-chip-bg-inactive:rgba(0,0,0,.35);--apple-icon-bg-inactive:rgba(0,0,0,.2);--apple-card-bg-active:#fff;--apple-chip-bg-active:rgba(255,255,255,.9);--apple-text-inactive:#fff;--apple-text-active:#1d1d1f;--apple-icon-inactive:rgba(142,142,147,.8);--apple-card-span-xl:2;--apple-card-span-desktop:3;--apple-card-span-tablet:4;--apple-card-span-mobile:6;--apple-card-span-xs:12}@media (max-width:767px){:root{--apple-card-height:70px;--apple-camera-height:200px;--apple-card-icon-size:42px;--apple-card-icon-font-size:28px;--apple-title-size:32px;--apple-section-title-size:20px;--apple-card-name-size:16px;--apple-card-state-size:14px;--apple-temp-font-size-regular:16px;--apple-temp-font-size-tall:40px;--apple-action-btn-size:40px;--apple-action-icon-size:22px;--apple-chip-height:36px;--apple-chip-icon-size:24px;--apple-chip-name-size:13px;--apple-chip-status-size:12px;--apple-page-padding:16px;--apple-page-padding-bottom:16px;--apple-section-gap:20px;--apple-card-gap:10px;--apple-card-padding:8px}}@media (max-width:399px){:root{--apple-page-padding:12px;--apple-page-padding-bottom:12px;--apple-temp-font-size-regular:16px;--apple-temp-font-size-tall:40px}}`;
export const liquidGlassCSS = `.liquid-glass-btn{border:none!important;border-radius:50%!important;color:rgba(255,255,255,.9)!important;cursor:pointer!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;outline:none!important;transition:all .2s ease!important;position:relative;isolation:isolate;transform:translateZ(0);will-change:transform,backdrop-filter;width:var(--apple-action-btn-size,40px)!important;height:var(--apple-action-btn-size,40px)!important;min-width:var(--apple-action-btn-size,40px)!important}.liquid-glass-btn:active{transform:scale(.95)}.liquid-glass-btn ha-icon{position:relative;z-index:2;--mdc-icon-size:var(--apple-action-icon-size,22px)}.liquid-glass-btn svg{position:relative;z-index:2}@media (prefers-reduced-motion:reduce){.liquid-glass-btn{transition:none!important}}.liquid-glass-transparent{background:rgba(0,0,0,.2)!important;backdrop-filter:blur(5px) saturate(1.5)!important;-webkit-backdrop-filter:blur(5px) saturate(1.5)!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.2),inset 0 1px 0 rgba(255,255,255,.25),inset 0 -1px 0 rgba(0,0,0,.1),0 2px 8px rgba(0,0,0,.12)!important}.liquid-glass-transparent::before{content:''!important;position:absolute!important;inset:-1px!important;border-radius:50%!important;padding:1px!important;background:linear-gradient(135deg,rgba(255,255,255,.4) 0%,rgba(255,255,255,.15) 25%,rgba(255,255,255,.25) 50%,rgba(255,255,255,.1) 75%,rgba(255,255,255,.35) 100%)!important;-webkit-mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0)!important;-webkit-mask-composite:xor!important;mask-composite:exclude!important;pointer-events:none!important;z-index:1!important}.liquid-glass-transparent:hover{background:rgba(0,0,0,.25)!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.3),inset 0 1px 0 rgba(255,255,255,.35),inset 0 -1px 0 rgba(0,0,0,.1),0 4px 12px rgba(0,0,0,.15)!important}.liquid-glass-transparent:hover::before{background:linear-gradient(135deg,rgba(255,255,255,.5) 0%,rgba(255,255,255,.2) 25%,rgba(255,255,255,.35) 50%,rgba(255,255,255,.15) 75%,rgba(255,255,255,.45) 100%)!important}.liquid-glass-transparent:active{background:rgba(0,0,0,.3)!important}.liquid-glass-dark{background:rgba(60,60,60,.6)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important}.liquid-glass-dark:hover{background:rgba(70,70,70,.7)!important}.liquid-glass-dark:active{background:rgba(80,80,80,.8)!important}.liquid-glass-light{background:rgba(120,120,120,.5)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important}.liquid-glass-light:hover{background:rgba(130,130,130,.6)!important}.liquid-glass-light:active{background:rgba(140,140,140,.7)!important}`;

let stylesInjected = false;
let tokensInjected = false;

export function injectDesignTokens(): void {
  if (tokensInjected) return;
  const e = document.getElementById('apple-design-tokens'); if (e) { tokensInjected = true; return; }
  const s = document.createElement('style'); s.id = 'apple-design-tokens'; s.textContent = designTokensCSS;
  document.head.appendChild(s); tokensInjected = true;
}

export function injectLiquidGlassStyles(): void {
  injectDesignTokens(); if (stylesInjected) return;
  const e = document.getElementById('liquid-glass-styles'); if (e) { stylesInjected = true; return; }
  const s = document.createElement('style'); s.id = 'liquid-glass-styles'; s.textContent = liquidGlassCSS;
  document.head.appendChild(s); stylesInjected = true;
}

export const LiquidGlassClasses = {
  headerButton: 'liquid-glass-btn liquid-glass-transparent',
  modalCancel: 'liquid-glass-btn liquid-glass-dark',
  modalDone: 'liquid-glass-btn liquid-glass-light',
} as const;
